<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NEDZLA-LAPTOP" failures="1" tests="1" name="MealPlanService" time="0.146" errors="0" timestamp="2024-04-03T01:47:27 CEST">
  <testcase classname="com.fithub.services.mealplan.test.suites.MealPlanServiceTest" name="testGetDailyMealByDay_ValidMealPlanIdIsProvided_ReturnsMealPlans" time="0.003">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.fithub.services.mealplan.test.suites.MealPlanServiceTest.testGetDailyMealByDay_ValidMealPlanIdIsProvided_ReturnsMealPlans(MealPlanServiceTest.java:92)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:154)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testGetDailyMealByDay_ValidMealPlanIdIsProvided_ReturnsMealPlans -->
</testsuite> <!-- MealPlanService -->
